# -*- coding: utf-8 -*-
"""
Created on Tue Jun 13 22:33:49 2017

@author: OMNISLO
"""

a_counter=0
c_counter=0
g_counter=0
t_counter=0

sequence="AGGGCGGGGAATACCCCATCACAGATAATCTTTATGGGGGGCGCTCAAATTACTTACCGCGTACGTCTATACTAGCCAAACAAACCTCCGAAATTGAGATTTCAATCGCCTTTGTTTTCGCGTGAATCCTCACTCGAGACCGACTAGCTATCTCCTCTGTTCCGCAATGAACAGCCGGCACCCTAGGCACAGAGCGAGATAGACTCAAGGACATCTCTTTGTCATCATTGCGCCCGGCAGGTAGATCTTCTTGCTAGACCAACACGATCGTGGGTTTGCATTGGATGTGGGCACCATCTGGGACCTACATGTCTGTTTGCAATAGTTCTGGGTCACGATCCCTTCTGGAGAGTACTACACTCGGGTTTGCGTCGGTCAGTAAGGATTCTAATCGCTATTGGCTGGTCCGGGAGTGGGACGTGTCGGGTAGGCGAATTACAGAAGGGCTGCAGGGCGATGTTTTTAAGATTGTTGTTGGCTAGAAGCCATAGATGCGGGGCTCGCCGGGTAGATGATTTTTGTCCGATTAATTGGCTGTACTGCGATGTCCGGCCCCCTTTGACGACCGATATACATTTGTCCAGCTTTTAGACTTCCCATAGATGCATGCTAACCAGTAAACTTTCCATCAATCGCAATTAACTTCAAAGTATACGCGCGTCGAAATCATGTTGCGGCATACAATTGTAGTGTATTCACCGGGAATCGGGCCAATGGGCCTATTTTCAGAGATAATGGGTATGTCCATCAACTATTTCGACGCGTAATCCAAGTGTGGAGACAGAACGGTGATTTGACCTATGACCTAATTCGAACGGTAA"

for x in sequence:
    if x=="A":
        a_counter+=1
    if x=="C":
        c_counter+=1
    if x=="G":
        g_counter+=1
    if x=="T":
        t_counter+=1

print(a_counter, c_counter, g_counter, t_counter)