# -*- coding: utf-8 -*-
"""
Created on Mon Feb 26 11:00:21 2018

@author: admin
"""

DNA = {'a':0, 'c':0, 'g':0, 't':0}

sequence="AGGGCGGGGAATACCCCATCACAGATAATCTTTATGGGGGGCGCTCAAATTACTTACCGCGTACGTCTATACTAGCCAAACAAACCTCCGAAATTGAGATTTCAATCGCCTTTGTTTTCGCGTGAATCCTCACTCGAGACCGACTAGCTATCTCCTCTGTTCCGCAATGAACAGCCGGCACCCTAGGCACAGAGCGAGATAGACTCAAGGACATCTCTTTGTCATCATTGCGCCCGGCAGGTAGATCTTCTTGCTAGACCAACACGATCGTGGGTTTGCATTGGATGTGGGCACCATCTGGGACCTACATGTCTGTTTGCAATAGTTCTGGGTCACGATCCCTTCTGGAGAGTACTACACTCGGGTTTGCGTCGGTCAGTAAGGATTCTAATCGCTATTGGCTGGTCCGGGAGTGGGACGTGTCGGGTAGGCGAATTACAGAAGGGCTGCAGGGCGATGTTTTTAAGATTGTTGTTGGCTAGAAGCCATAGATGCGGGGCTCGCCGGGTAGATGATTTTTGTCCGATTAATTGGCTGTACTGCGATGTCCGGCCCCCTTTGACGACCGATATACATTTGTCCAGCTTTTAGACTTCCCATAGATGCATGCTAACCAGTAAACTTTCCATCAATCGCAATTAACTTCAAAGTATACGCGCGTCGAAATCATGTTGCGGCATACAATTGTAGTGTATTCACCGGGAATCGGGCCAATGGGCCTATTTTCAGAGATAATGGGTATGTCCATCAACTATTTCGACGCGTAATCCAAGTGTGGAGACAGAACGGTGATTTGACCTATGACCTAATTCGAACGGTAA"

for x in sequence:
    if x=="A":
        DNA['a']+=1
    if x=="C":
        DNA['c']+=1
    if x=="G":
        DNA['g']+=1
    if x=="T":
        DNA['t']+=1

for x in DNA:
    print (DNA[x])